[project]
name = "qwir-blingz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "djangorestframework>=3.16.1",
    "httpx>=0.28.1",
    "pillow>=11.3.0",
    "python-dotenv>=1.1.1",
]
